### Experiment 2 - Build an Artificial Neural Network to implement Multi-Class Classification task using the Back-propagation algorithm and test the same using appropriate data sets.

#### Installing Necessary libraries globally

In [ ]:
!pip install numpy scikit-learn tensorflow pandas

Using Iris Dataset. download it from https://www.kaggle.com/datasets/uciml/iris?select=Iris.csv

#### Importing Necessary libraries

In [221]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Input
from tensorflow.keras.optimizers import Adam
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report, confusion_matrix

#### Loading the dataset

In [222]:
df = pd.read_csv('Iris.csv')

In [223]:
df.head(10)

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa
5   6            5.4           3.9            1.7           0.4  Iris-setosa
6   7            4.6           3.4            1.4           0.3  Iris-setosa
7   8            5.0           3.4            1.5           0.2  Iris-setosa
8   9            4.4           2.9            1.4           0.2  Iris-setosa
9  10            4.9           3.1            1.5           0.1  Iris-setosa

In [224]:
df.tail(10)

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
140  141            6.7           3.1            5.6           2.4   
141  142            6.9           3.1            5.1           2.3   
142  143            5.8           2.7            5.1           1.9   
143  144            6.8           3.2            5.9           2.3   
144  145            6.7           3.3            5.7           2.5   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
140  Iris-virginica  
141  Iris-virginica  
142  Iris-virginica  
143  Iris-virginica  
144  Iris-virginica  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica

In [225]:
df.shape

(150, 6)

In [226]:
df['Species'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [227]:
df.describe

<bound method NDFrame.describe of       Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-se

In [228]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


In [229]:
df.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

#### Shuffling the dataset

In [237]:
df = df.sample(frac=1, random_state=42).reset_index(drop=True) 

In [238]:
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0   70            5.6           2.5            3.9           1.1   
1  118            7.7           3.8            6.7           2.2   
2  135            6.1           2.6            5.6           1.4   
3   16            5.7           4.4            1.5           0.4   
4   84            6.0           2.7            5.1           1.6   

           Species  
0  Iris-versicolor  
1   Iris-virginica  
2   Iris-virginica  
3      Iris-setosa  
4  Iris-versicolor

#### Splitting values and labels

In [240]:
X = df.drop(['Id', 'Species'], axis=1).values
y = df['Species'].values

#### Encoding

In [241]:
encoder = OneHotEncoder(sparse_output=False)
y = encoder.fit_transform(y.reshape(-1, 1))

In [242]:
y

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0

#### Standardize the data

In [243]:
scaler = StandardScaler()
X = scaler.fit_transform(X)

#### Train-test split

In [244]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

#### Build the Model

In [245]:
model = Sequential([
    Input(shape=(4,)),       
    Dense(8, activation='relu'),  
    Dense(6, activation='relu'),
    Dense(3, activation='softmax') 
])

#### Compile the Model

In [246]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

#### Train the model

In [247]:
history = model.fit(X_train, y_train, epochs=50, batch_size=4, validation_split=0.2, verbose=1)

Epoch 1/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - accuracy: 0.3616 - loss: 1.1035 - val_accuracy: 0.2917 - val_loss: 1.1768
Epoch 2/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.3627 - loss: 1.0442 - val_accuracy: 0.2917 - val_loss: 1.1041
Epoch 3/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.4725 - loss: 0.9475 - val_accuracy: 0.3333 - val_loss: 1.0502
Epoch 4/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5548 - loss: 0.8963 - val_accuracy: 0.3333 - val_loss: 1.0120
Epoch 5/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5363 - loss: 0.8748 - val_accuracy: 0.3333 - val_loss: 0.9843
Epoch 6/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6008 - loss: 0.8151 - val_accuracy: 0.3333 - val_loss: 0.9664
Epoch 7/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.4933 - loss: 0.8774 - val_accuracy: 0.3750 - val_loss: 0.9498
Epoch 8/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.4829 - loss: 0.8737 - val_accuracy: 0.3750 - val_loss

#### Evaluate the model

In [249]:
loss, test_accuracy = model.evaluate(X_test, y_test, verbose=1)
print(f'Test Accuracy: {test_accuracy:.2f}')

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 0.9667 - loss: 0.3487
Test Accuracy: 0.97


#### Make Predictions

In [250]:
predictions = model.predict(X_test)
predicted_classes = np.argmax(predictions, axis=1)
true_classes = np.argmax(y_test, axis=1)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step


#### Calculate Accuracy

In [253]:
print("Classification Report:")
print(classification_report(true_classes, predicted_classes))

print("Confusion Matrix:")
print(confusion_matrix(true_classes, predicted_classes))

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       0.92      1.00      0.96        11
           2       1.00      0.88      0.93         8

    accuracy                           0.97        30
   macro avg       0.97      0.96      0.96        30
weighted avg       0.97      0.97      0.97        30

Confusion Matrix:
[[11  0  0]
 [ 0 11  0]
 [ 0  1  7]]


Learning Points - 
- **Various Types of Loss functions and their importance**
1) Binary Crossentropy (binary_crossentropy) --> used for Binary classification problems, where the target variable has two possible classes (0 or 1).
2) Categorical Crossentropy (categorical_crossentropy) --> used for Multi-class classification problems where the target variable has more than two classes and each class is mutually exclusive (i.e., each sample belongs to exactly one class).
3) Sparse Categorical Crossentropy (sparse_categorical_crossentropy) --> used for Multi-class classification problems, similar to categorical crossentropy, but the target labels are integers (not one-hot encoded). Note - instead of one-hot encoding the labels, you use integer class labels directly.
4) Mean Squared Error (mean_squared_error or mse) --> used for Regression tasks, where the output is continuous.
5) Mean Absolute Error (mean_absolute_error or mae) --> used for Regression tasks, but with less sensitivity to outliers compared to MSE.
6) Huber Loss (huber_loss) --> used for Regression tasks, especially when you want a loss function that is robust to outliers, combining the benefits of both MSE and MAE.

- **CODING SAMPLES**
1) For Classification Tasks --> model.compile(loss='X', optimizer='adam', metrics=['accuracy'])
replace X with the loss function
2) For Regression Tasks --> model.compile(loss='X' , optimizer = 'adam' , metrics =['mae'])

- **Various Types of Activation Functions and their use cases**
1) Sigmoid Activation Function --> Binary classification problems, Range: (0,1).
2) ReLU (Rectified Linear Unit) --> Hidden layers in most deep neural networks, Range: [0, ∞).
3) Leaky ReLU --> Leaky ReLU is used when the model suffers from "dying ReLU" issues, where neurons can get stuck during training and always output zero, Range: (-∞, ∞).
4) Tanh (Hyperbolic Tangent) --> Hidden layers in networks, especially for sequential data (e.g., RNNs), Range: (-1, 1).
5) Softmax --> Multiclass classification problems, Range: (0, 1) for each output, with the sum of all outputs equal to 1.

**For output layers** --> Generally, Sigmoid is used for binary classification problems, Softmax is used for Multiclass classification problems, and, for Regression tasks, the output layer typically does not use any activation function or Linear Activation (no activation).

- A general doubt arises,

the coding statmeent,

X = df.drop(['Id', 'Species'], axis=1).values

drops the columns 'Id' and 'Species' and takes rest of the columns in dataframe df

Why 'Id' attribute is dropped? --> Because it is irrelevant and not useful

And the function '.values' --> It returns a NumPy array. 

**Why the features are converted into NumPy Array rather than keeping them as a pandas DataFrame?**

--> Because, Machine learning libraries such as scikit-learn and TensorFlow/Keras typically expect the input data to be in the form of a NumPy array or a similar array-like structure. If you're performing feature scaling (e.g., with StandardScaler), or building deep learning models using TensorFlow or Keras, the underlying calculations are efficiently handled when data is passed as a NumPy array.

**Dataframe vs NumPy array**
1) pandas DataFrame:
a) More flexible for handling mixed data types (e.g., numbers, strings, dates), labeled rows and columns, and easy data manipulation (filtering, grouping, joining, etc.).
b) It is ideal for initial data cleaning, exploration, and feature engineering because of its rich functionalities.

2) NumPy Array:
a) Specifically designed for numerical data and optimized for speed and memory efficiency.
b) For machine learning tasks, once the data is cleaned and transformed into numerical values, it's converted into a NumPy array (or similar structures) because machine learning models in libraries like scikit-learn expect input in this format.